# Generated by Django 3.1.3 on 2020-11-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('post_code', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='materials/%Y/%m/%d')),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idle', models.BooleanField(default=False)),
                ('reparing', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='material.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_dept', to='material.department')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_supplier', to='material.supplier')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
