# Generated by Django 3.1.3 on 2020-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20201129_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
