# Generated by Django 3.1.3 on 2020-11-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20201130_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='material',
        ),
        migrations.AddField(
            model_name='district',
            name='material',
            field=models.ManyToManyField(related_name='material', to='material.Material'),
        ),
    ]
