# Generated by Django 3.1.3 on 2020-11-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20201130_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='material',
        ),
        migrations.AddField(
            model_name='district',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='material.material'),
        ),
    ]
