# Generated by Django 3.1.3 on 2020-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20201130_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='exampl@email.com', max_length=100),
        ),
    ]
