# Generated by Django 3.1.3 on 2020-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20201202_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
