# Generated by Django 3.1.3 on 2020-12-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_auto_20201203_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
