# Generated by Django 3.1.3 on 2020-12-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0010_auto_20201202_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Aizawl', 'Aizawl'), ('Lunglei', 'Lunglei'), ('Kolasib', 'Kolasib')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('UID', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.category')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
