# Generated by Django 3.1.3 on 2020-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
