# Generated by Django 3.1.3 on 2020-11-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0008_auto_20201130_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunglei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunglei_material', to='material.material')),
            ],
        ),
        migrations.CreateModel(
            name='Kolasib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kolasib_material', to='material.material')),
            ],
        ),
        migrations.CreateModel(
            name='Aizawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aizawl_material', to='material.material')),
            ],
        ),
    ]
