# Generated by Django 3.1.3 on 2020-12-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_delete_kolasib'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aizawl',
            options={'verbose_name': 'Aizawl'},
        ),
        migrations.AlterModelOptions(
            name='lunglei',
            options={'verbose_name': 'Lunglei'},
        ),
    ]
