# Generated by Django 3.1.3 on 2020-12-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_quote_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='msg',
            new_name='Message',
        ),
    ]
