# Generated by Django 3.1.3 on 2020-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0006_auto_20201201_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='supplier',
            field=models.CharField(max_length=50),
        ),
    ]
