# Generated by Django 3.1.3 on 2020-12-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0008_quote_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
    ]
