# Generated by Django 3.1.3 on 2020-12-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0010_auto_20201202_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='supplier_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='board_email',
        ),
    ]
