# Generated by Django 3.1.3 on 2020-12-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0011_auto_20201202_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aizawl',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lunglei',
            name='code',
        ),
    ]
