# Generated by Django 3.1.3 on 2020-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201128_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('', '--------'), ('Purchase Manager', 'Purchase Manager'), ('District Manager', 'District Manager')], max_length=20),
        ),
    ]
